services:
  server:
    container_name: castles-server
    build:
      context: ./Server/
      dockerfile: ./dockerfile
    ports:
      - "1488:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CASTLES_MINIO_SECRET_KEY=minioadmin
      - CASTLES_MINIO_ACCESS_KEY=minioadmin
    depends_on:
      - postgres
      - pgadmin
      - minio
      - redis

  postgres:
    container_name: castles-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: castles-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:9999"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 9999
    restart: unless-stopped

  minio:
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=porkchop
      - MINIO_ROOT_PASSWORD=bebrapidori

  redis:
    container_name: castles-caching
    image: redis:latest # todo: change from :latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=bebrapidori
      - REDIS_PORT=6379

volumes:
  postgres-data:
  minio_data:
    driver: local
